### PR TITLE
libtiff 4.1.0 rebuild

### PR DESCRIPTION
**Pull request by tobijk**
We need to rebuild libtiff against the latest available zstd package.

### CODE REVIEW

**Review by skupr-anaconda — COMMENTED** [review]
There are missing:
- `license_family: OTHER`
- `dev_url: https://gitlab.com/libtiff/libtiff`

To be updated:
- `home: https://libtiff.gitlab.io/libtiff/`
- `doc_url: http://www.simplesystems.org/libtiff/`
- `license: libtiff`, see https://gitlab.com/libtiff/libtiff/-/blob/v4.1.0/COPYRIGHT and https://spdx.org/licenses/libtiff.html

**Comment by cbouss** [comment]
Can you also add that line at the end of bld.bat? 
`copy "%LIBRARY_PREFIX%"\lib\tiff.lib "%LIBRARY_PREFIX%"\lib\libtiff.lib`

**Review by varlackc — COMMENTED** [review]
Need to add a `dev_url`
https://github.com/AnacondaRecipes/libtiff-feedstock/blob/8ad09d80c86af6ae121c42183e0dc11a084ec2f7/recipe/meta.yaml#L65&&L66

**Comment by tobijk** [comment]
@skupr-anaconda, @varlackc, thanks, all updated as suggested. @cbouss, it's already [there](https://github.com/AnacondaRecipes/libtiff-feedstock/blob/libtiff-4.1.0-rebuild/recipe/bld.bat#L17)

**Comment by tobijk** [comment]
Ah, no, it's not...

**Review by skupr-anaconda — APPROVED** [review]

**Pull request merged**
